### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by limcheekin** [alex-melnyk/music_app#1]
Thanks for sharing your craft.

May I know the license of the codes?

Appreciate if you could add a LICENSE file to the github repo.

Thank you.

**Comment by limcheekin** [comment]
Hi Oleksandr Melnyk,

Thanks for added a license.

Would you be interested in a platform to showcase your craft live on the mobile and web?
You are invited to look into Flutter Widgets Explorer: A platform to learn and showcase your Flutter Widgets.

Please go to the following link to find out more:
http://limcheekin.blogspot.com/2021/04/showcase-your-widget-with-flutter.html

Hope to hear from you soon.

**Comment by alex-melnyk** [comment]
Hi Lim, I'm not sure that I understand what exactly do you mean.
I don't mind in case, you want to include this example in your showcase app.

**Comment by limcheekin** [comment]
Thanks for quick response. You are the first one response to my invitation message.

Look like my message is not clear enough, a sign that I need to further improve it. 

I would like to invite you to clone the fluwix (the showcase app) repo and add your code example as a Flutter module and send me pull request. The takeaways are you can showcase your example live in an Android app, Fluwix.com and embedded HTML (as iframe) in your blog post. Of course it is volunteer basis, depends on your interest and time on hand.

Appreciate you granted me the permission to include the example in my showcase app. If this is a no go for you, I might go ahead myself.

Thank you.

**Comment by alex-melnyk** [comment]
Looks great, this project developed as an example for mobile, and on the web, it will not have gestures behavior like on mobile. I have a few libraries that might be included in your app, take a look at this list:

[https://github.com/alex-melnyk/flutter_advanced_segment](https://github.com/alex-melnyk/flutter_advanced_segment)
[https://github.com/alex-melnyk/flutter_advanced_calendar](https://github.com/alex-melnyk/flutter_advanced_calendar)
[https://github.com/alex-melnyk/flutter_advanced_progress](https://github.com/alex-melnyk/flutter_advanced_progress)
[https://github.com/alex-melnyk/flutter_advanced_switch](https://github.com/alex-melnyk/flutter_advanced_switch)
[https://github.com/alex-melnyk/flutter_advanced_avatar](https://github.com/alex-melnyk/flutter_advanced_avatar)

**Comment by limcheekin** [comment]
Thanks for sharing the libraries.

For all showcases I included in my showcase app, I always gave the full credit to the code owner (which specified in the LICENSE file). For the music_app, I'm a bit confuse, should I put your name Alex Melnyk or Oleksandr Melnyk?

Hope to hear from you soon! :)

Thank you.
